ldos-project/KernMLOps

- README.md
@patrickkenney9801 Please finish then record demo.
> Added README stub for tutorial for base levels of collection

- .gitignore
- .pre-commit-config.yaml
- module/Makefile
- module/fstore/Makefile
- module/fstore/fstore.c
- module/test/register_func.cpp
Dependent PR on 6.12 config, please merge that first.
> Initial Build infra for fstore kernel module

- Dockerfile.dev
Super useful tool for debugging issues with kernel configs and compiles
> feat: bpftrace in dockerfile by default

- Dockerfile.dev
- Makefile
- python/kernmlops/kernmlops_benchmark/memcached.py
- python/kernmlops/kernmlops_benchmark/mongodb.py
- python/kernmlops/kernmlops_benchmark/redis.py
- scripts/settings.xml
- scripts/setup-benchmarks/install-ycsb.sh
- scripts/setup-benchmarks/ycsb_runner.py
YCSB needed to forward the `recordcount` and also needed to be updated to include deletes.
> YCSB needed to be runnable + deletes

- python/kernmlops/cli/collect.py
Creates separate thread for polling ebpf.
> fix: poll ebpf in a separate thread

- Makefile
- python/kernmlops/kernmlops_benchmark/mongodb.py
- requirements.txt
This puts all management for mongodb in kernmlops_benchmark
> fix: properly support mongodb benchmark

- python/kernmlops/kernmlops_benchmark/redis.py
- scripts/setup-benchmarks/install-ycsb.sh
Also add redis fixed code to print out more info
> fix: YCSB installation with deletion is correct

- python/kernmlops/kernmlops_benchmark/benchmark.py
Expands support for benchmark initializers for larger memory workloads
> feat: Add overcommit memory as a benchmark setup

- .gitignore
- benchmark/zswap/parse_results.py
- benchmark/zswap/remote_runner.py
- benchmark/zswap/setup.sh
Wasn't sure which directory was best for them, but placed in `benchmark/` for now... lmk if you want me to change it
> Add zswap benchmark experiments

- tutorial.ipynb
Use polars to add filtering to the tutorial.
> chore: Add filtering to tutorial

- python/kernmlops/data_collection/bpf_instrumentation/bpf/mm_trace_rss_stat.bpf.c
- python/kernmlops/data_collection/bpf_instrumentation/mm_rss_stat.py
Also should fix the issue with different kernel versions
> fix: rss is now accurate in multithreaded environments

- python/kernmlops/kernmlops_benchmark/memcached.py
- python/kernmlops/kernmlops_benchmark/redis.py
Creates the server with memcached from kermit itself.
> fix: Properly support memcached

- tutorial.ipynb
> fix: Make tutorial more inside notebook

- python/kernmlops/data_collection/bpf_instrumentation/__init__.py
- python/kernmlops/data_collection/bpf_instrumentation/bpf/madvise.bpf.c
- python/kernmlops/data_collection/bpf_instrumentation/bpf/unmap_range.bpf.c
- python/kernmlops/data_collection/bpf_instrumentation/madvise.py
- python/kernmlops/data_collection/bpf_instrumentation/unmap_range.py
- python/kernmlops/data_schema/generic_table.py
Adds madvise and unmap range probes to enable studying of madvise.
> Madvise and Unmap Range

- Dockerfile.dev
- config/redis.conf
- config/redis_always.yaml
- config/redis_madvise.yaml
- config/redis_never.yaml
- python/kernmlops/data_collection/bpf_instrumentation/bpf/madvise.bpf.c
- python/kernmlops/data_collection/bpf_instrumentation/madvise.py
- python/kernmlops/kernmlops_benchmark/redis.py
Small config changes to larger data.
Also munmap probes to collect data
> feat: Add munmap to madvise information

- Dockerfile.dev
- config/redis.conf
- python/kernmlops/kernmlops_benchmark/redis.py
This allows users to use a tcmalloc tag on overrides to have redis use tcmalloc.
> feat: support redis with tcmalloc

- python/kernmlops/kernmlops_benchmark/redis.py
- requirements.txt
Allows a sleep to be specified as a timeparse string
> feat: add delays to redis

- README.md
- scripts/install_prerequesites_ubuntu_24_04.sh
This should use scripts/install_prerequesites_ubuntu_24_04.sh to put you in the right setup easily.
> fix: Make install just one script

- python/kernmlops/kernmlops_benchmark/redis.py
- tutorial.ipynb
* Fix an issue with input buffering where pexpect must await EOF before termination
> fix: Fully fix the tutorial

- scripts/install_prerequesites_ubuntu_24_04.sh
- tutorial.ipynb
* update the install script to make it cleaner and consistent
* make the script separate installation and update
> fix: tutorial needs a fix to make it the same

- python/kernmlops/kernmlops_benchmark/memcached.py
Add a repeat feature to memcached that allow the benchmark command to run for multiple iterations
> feat: add repeat to memcached

- Dockerfile.dev
- README.md
- scripts/setup_prep_env.sh
* Updates Dockerfile.dev
* Creates pyproject.toml
* Fix installation script
* Update README
> chore: use uv instead of pipenv for installation

- python/kernmlops/data_collection/bpf_instrumentation/collapse_huge_page.py
This will need to be revisited in the future.
> chore: Small fix to make collapse viable
